In [36]:
!pip install ultralytics

Requirement already satisfied: ultralytics in /usr/local/lib/python3.12/dist-packages (8.4.14)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (4.13.0.92)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.16.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.10.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.25.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.31.0)
Requirement already satisfied: ultralytics-thop>=2.0.18 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.18)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2026.1.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.8.0->ultralytics) (1.3.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)

In [37]:
!pip install PyYAML

Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (6.0.3)

In [41]:
from ultralytics import YOLO

In [43]:
from google.colab import drive
drive.mount('/drive')
import os
os.chdir('/drive/MyDrive/Computer_Vision_Assignment_2')

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).

In [44]:
# Load a pretrained segmentation model like YOLO26n-seg
model = YOLO("yolo26n.pt")  # load a pretrained model (recommended for training)

In [45]:
dataset_yaml = "car-object-detection/data.yaml"

In [46]:
import pandas as pd
import glob
import os
import yaml

In [47]:
with open(os.path.join(dataset_yaml), 'r') as file:
    config_data = yaml.safe_load(file)

# Now you can work with the data as a Python dictionary or list
# Access specific elements
class_names = {}
for i, value in enumerate(config_data['names']):
    class_names[i] = value

In [48]:
IMAGES_PATH = os.path.join('car-object-detection/train/images/')
LABELS_PATH = os.path.join('car-object-detection/train/labels/')

In [49]:
#%%
def create_yolo_dataframe(image_dir, label_dir):
    """
    Creates a pandas DataFrame with image file names and object labels from a YOLO dataset.

    Args:
        image_dir (str): Path to the directory containing images.
        label_dir (str): Path to the directory containing YOLO .txt label files.

    Returns:
        pd.DataFrame: A DataFrame with 'filename' and 'label' columns.
    """


    image_files = glob.glob(os.path.join(image_dir, '*.*')) # Adjust file extensions if needed
    data_dict = {}
    data = []
    separator = ","

    # 3. Iterate through each image file
    for img_path in image_files:
        img_filename = os.path.basename(img_path)

        # Construct the corresponding label file path
        label_filename = os.path.splitext(img_filename)[0] + '.txt'
        label_path = os.path.join(label_dir, label_filename)


        # 4. Check if the label file exists and parse it
        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                labels = []
                key = None
                for line in f.readlines():
                    # Each line has format: class_id center_x center_y width height
                    class_id = int(line.strip().split(' ')[0])
                    label_name = class_names[class_id]
                    labels.append(label_name)
                    key = separator.join(labels)
                if key not in data_dict:
                    data_dict[key] = []
                    data_dict[key].append(img_filename.split('.')[0])
                else:
                   data_dict[key].append(img_filename.split('.')[0])

    for key in data_dict.keys():
        values = separator.join(data_dict[key])
        data.append({'label': key, 'filename': values})

    # 5. Create the pandas DataFrame
    df = pd.DataFrame(data)
    return df

In [50]:
# Create the DataFrame
yolo_df = create_yolo_dataframe(IMAGES_PATH, LABELS_PATH)

# Display the first few rows of the DataFrame
yolo_df.head()

,label,filename
0,"windshield,bumper,hood","video_mp4-0035_jpg,video_mp4-0042_jpg"
1,"windshield,tire,wheel,wheel,window,door,side_m...",video_mp4-0125_jpg
2,"windshield,emblem,emblem,bumper,hood","video_mp4-0030_jpg,video_mp4-0019_jpg,video_mp..."
3,"windshield,emblem,bumper,hood","video_mp4-0027_jpg,video_mp4-0017_jpg,video_mp..."
4,"tire,tire,tire,tire,wheel,wheel,wheel","video_mp4-0085_jpg,video_mp4-0069_jpg"

In [51]:
# Train the model on the Carparts Segmentation dataset
results = model.train(data=dataset_yaml, epochs=100, imgsz=640)

Ultralytics 8.4.14 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=car-object-detection/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/drive/MyDrive/Computer_Vision_Assignment_2/runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=15

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    247026  ultralytics.nn.modules.head.Detect           [15, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,509,650 parameters, 2,509,650 gradients, 5.8 GFLOPs

Transferred 606/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.9±0.6 ms, read: 9.8±6.7 MB/s, size: 31.0 KB)
train: Scanning /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/train/labels.cache... 196 images, 26 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 196/196 48.4Mit/s 0.0s
WARNING ⚠️ Box and segment counts should be equal, but got len(segments) = 1107, len(boxes) = 1108. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 1.5±1.1 ms, read: 5.1±2.2 MB/s, size: 21.9 KB)
val: Scanning /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/labels.cache... 56 images, 13 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 56/56 1.3Mit/s 0.0s
val: /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/images/video_mp4-0048_jpg.rf.a851042fcb96a8bad53e7fd146619481.jpg: 1 duplicate labels removed
val: /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/images/video_mp4-0126_jpg.rf.67bcbf0b18629aa8c0e24895d3c7f65f.jpg: 1 duplicate labels removed
val: /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/images/video_mp4-0138_jpg.rf.d7af0f92776615649af2eb8e08ef83dc.jpg: 1 duplicate labels removed
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000526, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /drive/MyDrive/Computer_Vision_Assignment_2/runs/detect/train7/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /drive/MyDrive/Computer_Vision_Assignment_2/runs/detect/train7
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100      2.73G      1.484      5.379     0.0128         37        640: 100% ━━━━━━━━━━━━ 13/13 1.6it/s 7.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.1it/s 0.5s
                   all         56        302          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/100      2.89G      1.356      5.343    0.01077         35        640: 100% ━━━━━━━━━━━━ 13/13 3.3it/s 3.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 5.5it/s 0.4s
                   all         56        302          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/100       2.9G      1.199      5.159   0.009223         36        640: 100% ━━━━━━━━━━━━ 13/13 3.1it/s 4.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.4it/s 0.5s
                   all         56        302      0.094     0.0323     0.0558     0.0473

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/100       2.9G      1.137      4.958   0.008718         51        640: 100% ━━━━━━━━━━━━ 13/13 2.6it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.1it/s 0.5s
                   all         56        302     0.0334      0.188     0.0516     0.0343

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/100       2.9G      1.055      4.779   0.008365         36        640: 100% ━━━━━━━━━━━━ 13/13 3.4it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.2it/s 0.5s
                   all         56        302     0.0086      0.223     0.0543     0.0465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/100       2.9G      1.071      4.374   0.008644         42        640: 100% ━━━━━━━━━━━━ 13/13 2.3it/s 5.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.6it/s 0.4s
                   all         56        302      0.911     0.0384     0.0865      0.074

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/100       2.9G      1.042      4.142   0.007838         47        640: 100% ━━━━━━━━━━━━ 13/13 3.5it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         56        302      0.779     0.0838      0.112     0.0936

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/100       2.9G      1.038      4.036   0.007437         51        640: 100% ━━━━━━━━━━━━ 13/13 3.4it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         56        302      0.691      0.161      0.142      0.113

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/100       2.9G      1.048      3.748   0.007581         25        640: 100% ━━━━━━━━━━━━ 13/13 2.6it/s 4.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s
                   all         56        302      0.682      0.162      0.157      0.122

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/100       2.9G      1.039      3.582   0.007317         28        640: 100% ━━━━━━━━━━━━ 13/13 3.4it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s
                   all         56        302      0.644      0.183      0.196      0.148

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/100       2.9G      1.015      3.513   0.007828         35        640: 100% ━━━━━━━━━━━━ 13/13 2.4it/s 5.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.6it/s 0.8s
                   all         56        302      0.637      0.247      0.245      0.183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/100       2.9G      1.013      3.499   0.007185         47        640: 100% ━━━━━━━━━━━━ 13/13 3.5it/s 3.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         56        302      0.638      0.269      0.253      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/100       2.9G     0.9778      3.305   0.007299         36        640: 100% ━━━━━━━━━━━━ 13/13 3.5it/s 3.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.6it/s 0.6s
                   all         56        302      0.641      0.268      0.283      0.221

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/100       2.9G      1.023      3.122   0.007373         65        640: 100% ━━━━━━━━━━━━ 13/13 2.5it/s 5.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         56        302      0.585      0.328      0.304      0.236

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/100       2.9G      0.942      3.088   0.006817         32        640: 100% ━━━━━━━━━━━━ 13/13 3.4it/s 3.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         56        302      0.676      0.309      0.323      0.251

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/100       2.9G      0.953      2.983   0.006957         43        640: 100% ━━━━━━━━━━━━ 13/13 2.6it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.6it/s 0.8s
                   all         56        302      0.659      0.317      0.387      0.294

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/100       2.9G     0.9539      2.957   0.007249         36        640: 100% ━━━━━━━━━━━━ 13/13 3.2it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.2it/s 0.5s
                   all         56        302      0.532      0.391      0.374      0.292

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/100       2.9G     0.9377      2.968   0.008125         19        640: 100% ━━━━━━━━━━━━ 13/13 3.2it/s 4.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.3it/s 0.6s
                   all         56        302      0.561      0.385       0.42      0.317

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/100       2.9G     0.9511      2.825    0.00682         40        640: 100% ━━━━━━━━━━━━ 13/13 3.2it/s 4.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.0it/s 0.5s
                   all         56        302      0.611       0.38      0.433      0.326

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/100       2.9G     0.8931      2.643   0.006824         50        640: 100% ━━━━━━━━━━━━ 13/13 3.4it/s 3.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.9it/s 0.5s
                   all         56        302      0.555      0.416      0.421      0.328

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/100       2.9G     0.9278      2.759   0.006994         47        640: 100% ━━━━━━━━━━━━ 13/13 2.4it/s 5.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.8it/s 0.5s
                   all         56        302      0.614      0.377       0.44      0.333

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/100       2.9G      1.016      2.724    0.00727         26        640: 100% ━━━━━━━━━━━━ 13/13 3.3it/s 3.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.7it/s 0.5s
                   all         56        302      0.643      0.369      0.457      0.349

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/100       2.9G       0.95      2.639   0.007279         21        640: 100% ━━━━━━━━━━━━ 13/13 3.4it/s 3.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.5it/s 0.8s
                   all         56        302      0.524      0.447      0.482      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/100       2.9G     0.9794      2.422   0.006522         29        640: 100% ━━━━━━━━━━━━ 13/13 2.7it/s 4.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.0it/s 0.5s
                   all         56        302      0.647      0.427      0.506        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/100       2.9G      0.942      2.467   0.006722         18        640: 100% ━━━━━━━━━━━━ 13/13 3.5it/s 3.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.1it/s 0.5s
                   all         56        302      0.632      0.448      0.515       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/100       2.9G     0.8954      2.552    0.00738         22        640: 100% ━━━━━━━━━━━━ 13/13 2.4it/s 5.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.9it/s 0.5s
                   all         56        302       0.56      0.454      0.517      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/100       2.9G     0.9492      2.451   0.006392         26        640: 100% ━━━━━━━━━━━━ 13/13 3.7it/s 3.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.8it/s 0.7s
                   all         56        302      0.548      0.476      0.508      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/100       2.9G     0.8611      2.356   0.006354         60        640: 100% ━━━━━━━━━━━━ 13/13 2.4it/s 5.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 2.5it/s 0.8s
                   all         56        302      0.483      0.528      0.511      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/100       2.9G     0.8854      2.388   0.006251         39        640: 100% ━━━━━━━━━━━━ 13/13 3.3it/s 4.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.9it/s 0.5s
                   all         56        302      0.567      0.466      0.516      0.418

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/100       2.9G     0.8808      2.229   0.005953         33        640: 100% ━━━━━━━━━━━━ 13/13 3.5it/s 3.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.3it/s 0.5s
                   all         56        302      0.411      0.588      0.517      0.413

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/100       2.9G     0.8984      2.292   0.006692         19        640: 100% ━━━━━━━━━━━━ 13/13 2.4it/s 5.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 4.1it/s 0.5s
                   all         56        302      0.456      0.602      0.526      0.425

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/100       2.9G     0.8801      2.213   0.006446         27        640: 100% ━━━━━━━━━━━━ 13/13 3.2it/s 4.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.0it/s 0.7s
                   all         56        302      0.543      0.567      0.528      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/100       2.9G     0.8881      2.213   0.006254         59        640: 100% ━━━━━━━━━━━━ 13/13 2.6it/s 5.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 2/2 3.2it/s 0.6s

In [52]:
# After training, you can validate the model's performance on the validation set
results = model.val()

Ultralytics 8.4.14 🚀 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,377,761 parameters, 0 gradients, 5.2 GFLOPs
val: Fast image access ✅ (ping: 0.5±0.3 ms, read: 8.9±6.1 MB/s, size: 22.7 KB)
val: Scanning /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/labels.cache... 56 images, 13 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 56/56 18.1Mit/s 0.0s
val: /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/images/video_mp4-0048_jpg.rf.a851042fcb96a8bad53e7fd146619481.jpg: 1 duplicate labels removed
val: /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/images/video_mp4-0126_jpg.rf.67bcbf0b18629aa8c0e24895d3c7f65f.jpg: 1 duplicate labels removed
val: /drive/MyDrive/Computer_Vision_Assignment_2/car-object-detection/valid/images/video_mp4-0138_jpg.rf.d7af0f92776615649af2eb8e08ef83dc.jpg: 1 duplicate labels removed
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.4it/s 2.8s
                   all         56        302      0.621      0.648      0.678      0.571
                bumper         21         31      0.666      0.839       0.84      0.755
                  door         13         21      0.617      0.524      0.656      0.526
                emblem         22         30      0.778        0.7      0.748      0.537
               exhaust          2          2      0.244        0.5        0.5        0.4
             fog_light          6          7      0.531      0.571      0.549      0.378
                grille         10         19      0.732      0.842      0.863        0.8
             headlight         11         16      0.678      0.875      0.859      0.789
                  hood         21         25      0.751      0.725      0.799      0.754
           side_mirror         15         23      0.735      0.609       0.71      0.487
             taillight          5          6      0.312      0.531      0.362      0.321
                  tire         15         25      0.609       0.56      0.657        0.5
                 trunk          4          4       0.49      0.724      0.505      0.454
                 wheel         18         26      0.611      0.615      0.732      0.612
                window         19         39      0.707      0.462      0.572       0.45
            windshield         28         28      0.859      0.643      0.827      0.802
Speed: 9.5ms preprocess, 8.8ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to /drive/MyDrive/Computer_Vision_Assignment_2/runs/detect/val7

In [53]:
from datasets import load_dataset
from PIL import Image
import numpy as np
import pandas as pd, pyarrow

In [127]:
ds = load_dataset("aegean-ai/rav4-exterior-images", split="train")

In [147]:
rows = []

for i, data in enumerate(ds):
  filtered_df = None

  img = data["image"]
  row = None # Initialize row to None for cases where no boxes are found

  # Predict on the single image
  # returns a list of Results objects (length 1)
  results = model.predict(img, verbose=False)
  if not results:
    continue

  result = results[0]
  # Access bounding boxes for this frame
  boxes = result.boxes
  # Extract bounding boxes for the DataFrame in the next steps
  xyxy = []
  class_labels = []
  score = []

  # Append all bounding boxes as a list of lists, where each inner list is [x_min, y_min, x_max, y_max] for one box
  # boxes.xyxy is already a tensor of shape (N, 4), so .tolist() on it directly works.
  xyxy = (boxes.xyxy.cpu().numpy()).tolist()

  for i in range(len(boxes)):
    score.append(float(boxes.conf[i].cpu().item()*100))
    class_id = int(boxes.cls[i].cpu().item())
    class_labels.append(result.names[class_id])

  yolo_df['has_match'] = yolo_df['label'].apply(lambda label_str: any(item in label_str.split(',') for item in names_to_find) if label_str is not None else False)

  # Create a new DataFrame with matching rows
  filtered_df = (yolo_df[yolo_df['has_match'] == True].copy()).reset_index(drop=True)

  frame_index = []
  file_names = []
  for index, filenames_str in enumerate(filtered_df['filename']):
    file_names.append(filenames_str)
    # Safely extract frame index if the format matches 'video_mp4-XXXX_jpg'
    parts = filenames_str.split('-')
    frame_idx_part = parts[1].split('_')[0]
    frame_index.append(frame_idx_part)

    # Populate the row dictionary with extracted information
    row = {
        "video_id": file_names[0:5], # This takes up to 5 matching training filenames
        "frame_index": frame_index[0:5], # This takes up to 5 matching training frame indices
        "class_label": class_labels,      # List of all detected labels in the current `ds` image
        "bounding_box": xyxy,            # List of all detected bounding boxes in the current `ds` image
        "confidence_score": score,       # List of all detected confidence scores in the current `ds` image
    }
  rows.append(row) # Append the row (or None if no boxes)

In [148]:
df = pd.DataFrame(rows)
df.to_parquet("video_detections.parquet", engine="pyarrow", index=False)

In [149]:
df = pd.DataFrame(rows)
df.to_parquet("video_detections.parquet", engine="pyarrow", index=False)

In [150]:
!pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.24.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (0.24.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface_hub) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface_hub) (0.1.2)

In [151]:
from huggingface_hub import login, upload_file

In [152]:
login('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')

upload_file(
    path_or_fileobj="video_detections.parquet",  # Path to your file in Colab
    path_in_repo="video_detections.parquet",     # Path where to save in the repo
    repo_id="shesel08/car-parts-segmentation",   # Your repo ID
    repo_type="dataset",             # "dataset" or "model"
)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  video_detections.parquet    : 100%|##########| 10.6kB / 10.6kB

CommitInfo(commit_url='https://huggingface.co/datasets/shesel08/car-parts-segmentation/commit/6077ef0ab4e7a1a4b22c9e7be3a710a5ccdbea90', commit_message='Upload video_detections.parquet with huggingface_hub', commit_description='', oid='6077ef0ab4e7a1a4b22c9e7be3a710a5ccdbea90', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/shesel08/car-parts-segmentation', endpoint='https://huggingface.co', repo_type='dataset', repo_id='shesel08/car-parts-segmentation'), pr_revision=None, pr_num=None)

In [153]:
car_df = load_dataset("shesel08/car-parts-segmentation", split="train")

video_detections.parquet:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
df = pd.DataFrame(car_df)
df.head()

,video_id,frame_index,class_label,bounding_box,confidence_score
0,"[video_mp4-0146_jpg, video_mp4-0149_jpg, video...","[0146, 0149, 0136, 0144, 0141]","[hood, tire]","[[1570.37451171875, 882.6976318359375, 2302.80...","[73.36764931678772, 50.15265941619873]"
1,"[video_mp4-0146_jpg, video_mp4-0149_jpg, video...","[0146, 0149, 0136, 0144, 0141]","[bumper, bumper]","[[358.60137939453125, 1412.212646484375, 612.2...","[87.54261136054993, 35.89290976524353]"
2,"[video_mp4-0146_jpg, video_mp4-0149_jpg, video...","[0146, 0149, 0136, 0144, 0141]",[bumper],"[[433.3812561035156, 1419.4476318359375, 683.8...",[34.62643921375275]
3,"[video_mp4-0146_jpg, video_mp4-0149_jpg, video...","[0146, 0149, 0136, 0144, 0141]","[bumper, headlight, hood, hood, bumper, bumper...","[[1769.7755126953125, 1365.0447998046875, 2607...","[68.21022629737854, 53.54514122009277, 36.0281..."
4,"[video_mp4-0146_jpg, video_mp4-0149_jpg, video...","[0146, 0149, 0136, 0144, 0141]",[bumper],"[[370.69036865234375, 1199.04736328125, 551.25...",[66.89255237579346]